services:
    frankenphp:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped

        environment:
            APP_ENV: prod
            DOMAIN_NAME: matnas.pl
            DEFAULT_URI: https://matnas.pl

            POSTGRES_DB: communicator_prod
            POSTGRES_USER: postgres
            DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@database:5432/communicator_prod?serverVersion=16&charset=utf8

            SYMFONY_DECRYPTION_SECRET: ${SYMFONY_DECRYPTION_SECRET:-}

            MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET}
            MERCURE_URL: http://localhost:8080/.well-known/mercure
            MERCURE_PUBLIC_URL: https://matnas.pl/.well-known/mercure
            MERCURE_HUB_URL: http://localhost:8080/.well-known/mercure
            MAILER_DSN: "null://null"

        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: communicator_prod
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d communicator_prod"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - database_data_prod:/var/lib/postgresql/data


volumes:
    database_data_prod:
    caddy_data:
    caddy_config:
