# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            int $sessionLifetime: '%env(int:SESSION_LIFETIME)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    Redis:
        class: Redis
        factory: ['App\Factory\RedisFactory', 'create']
        arguments:
            $dsn: '%env(REDIS_DSN)%'

    App\Session\FixedLifetimeRedisSessionHandler:
        arguments:
            $redis: '@Redis'
            $options:
                prefix: 'sf_sess:'
                ttl: '%env(int:SESSION_LIFETIME)%'

when@test:
    services:
        app.mercure.mock_publisher:
            class: App\Tests\Mock\MockMercurePublisher

        Symfony\Component\Mercure\HubInterface:
            class: Symfony\Component\Mercure\MockHub
            arguments:
                $url: 'https://localhost/.well-known/mercure'
                $jwtProvider: !service
                    class: Symfony\Component\Mercure\Jwt\StaticTokenProvider
                    arguments: ['test_token']
                $publisher: '@app.mercure.mock_publisher'

        Redis:
            class: Redis
